apiVersion: apps/v1
kind: Deployment
metadata:
  name: vproapp
  labels:
    app: vproapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vproapp
  template:
    metadata:
      labels:
        app: vproapp
    spec:
      initContainers:
        - name: init-mydb
          image: busybox:1.28
          command:
            [
              'sh',
              '-c',
              'until nslookup vprodb-service.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for vprodb service; sleep 2; done',
            ]
        - name: init-memcached
          image: busybox:1.28
          command:
            [
              'sh',
              '-c',
              'until nslookup vpromc-service.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for vprocache01 service; sleep 2; done',
            ]
        - name: init-rabbitmq
          image: busybox:1.28
          command:
            [
              'sh',
              '-c',
              'until nslookup vprormq-service.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for vpromq01 service; sleep 2; done',
            ]
      containers:
        - name: vproapp
          image: routparesh/vproapp:latest
          imagePullPolicy: Always
